import fs from "node:fs";
import path from "node:path";
import type { ConfigHealth, FileHealth } from "@palserver/shared";
import type { DriverContext } from "./driver.js";
import type { InstanceRecord } from "./store.js";
import { serverRoot } from "./native.js";
import { renderPalWorldSettingsIni } from "./settings-ini.js";

/**
 * Detects a corrupted PalWorldSettings.ini or Engine.ini on disk and can
 * regenerate a fresh one. These files can be broken by a hand edit, a bad
 * adopted install, or a half-written save — the game then silently starts a
 * new world or ignores the config, which is worse than a clear error.
 *
 * "Corrupted" here means: the file exists but its structure is unusable.
 * Regeneration backs the bad file up first (never a silent data loss), then
 * writes a valid one — the world ini from the agent's stored settings (the
 * source of truth), the engine ini as a minimal valid file.
 */

const PLATFORM_DIR = process.platform === "win32" ? "WindowsServer" : "LinuxServer";
const configDir = (root: string) => path.join(root, "Pal", "Saved", "Config", PLATFORM_DIR);
const worldIni = (root: string) => path.join(configDir(root), "PalWorldSettings.ini");
const engineIni = (root: string) => path.join(configDir(root), "Engine.ini");

const rel = (root: string, file: string) => path.relative(root, file).split(path.sep).join("/");

/** A line the ini parser should recognise: blank, comment, section, key=value. */
const INI_LINE = /^\s*($|;|#|\[.+\]\s*$|[^=\s][^=]*=)/;

function checkStructure(text: string): string | null {
  const lines = text.split(/\r?\n/);
  let sawSection = false;
  for (const raw of lines) {
    const line = raw.trim();
    if (line === "") continue;
    if (/^\[.+\]$/.test(line)) {
      sawSection = true;
      continue;
    }
    if (/^\[/.test(line) && !/\]$/.test(line)) return "區段標頭未正確關閉";
    if (!INI_LINE.test(raw)) return `無法解析的內容:「${line.slice(0, 40)}」`;
  }
  if (!sawSection) return "找不到任何區段標頭";
  return null;
}

function worldHealth(root: string): FileHealth {
  const file = worldIni(root);
  if (!fs.existsSync(file)) {
    return { exists: false, corrupted: false, path: rel(root, file) };
  }
  const text = fs.readFileSync(file, "utf8");
  const structural = checkStructure(text);
  if (structural) return { exists: true, corrupted: true, reason: structural, path: rel(root, file) };

  // PalWorldSettings.ini specifically needs the world-settings section and a
  // balanced OptionSettings=(...) tuple; the game rejects a broken one.
  if (!/\[\/Script\/Pal\.PalGameWorldSettings\]/.test(text)) {
    return { exists: true, corrupted: true, reason: "缺少 PalGameWorldSettings 區段", path: rel(root, file) };
  }
  const opt = /OptionSettings\s*=\s*\((.*)\)\s*$/m.exec(text);
  if (!opt) {
    return { exists: true, corrupted: true, reason: "OptionSettings 缺失或括號不完整", path: rel(root, file) };
  }
  return { exists: true, corrupted: false, path: rel(root, file) };
}

function engineHealth(root: string): FileHealth {
  const file = engineIni(root);
  if (!fs.existsSync(file)) {
    return { exists: false, corrupted: false, path: rel(root, file) };
  }
  const structural = checkStructure(fs.readFileSync(file, "utf8"));
  return {
    exists: true,
    corrupted: structural !== null,
    reason: structural ?? undefined,
    path: rel(root, file),
  };
}

export function getConfigHealth(rec: InstanceRecord, ctx: DriverContext): ConfigHealth {
  if (rec.backend !== "native") {
    const na: FileHealth = { exists: false, corrupted: false, path: null };
    return { supported: false, world: na, engine: na };
  }
  const root = serverRoot(rec, ctx);
  return { supported: true, world: worldHealth(root), engine: engineHealth(root) };
}

function backupCorrupt(file: string): void {
  if (!fs.existsSync(file)) return;
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  fs.renameSync(file, `${file}.corrupt-${stamp}.bak`);
}

export function regenerateConfig(
  rec: InstanceRecord,
  ctx: DriverContext,
  which: "world" | "engine",
): { path: string; backedUp: boolean } {
  const root = serverRoot(rec, ctx);
  fs.mkdirSync(configDir(root), { recursive: true });

  const file = which === "world" ? worldIni(root) : engineIni(root);
  const existed = fs.existsSync(file);
  backupCorrupt(file);

  if (which === "world") {
    // The store's settings are the source of truth; write them out fresh.
    fs.writeFileSync(file, renderPalWorldSettingsIni(rec.settings));
  } else {
    // A minimal valid Engine.ini; the engine fills in its own defaults, and
    // the 效能 tab writes overrides into it as needed.
    fs.writeFileSync(file, "; regenerated by palserver GUI\n");
  }
  return { path: rel(root, file), backedUp: existed };
}
